### ISSUE TITLE
Required Parameter without a type

### ISSUE THREAD

**Issue by justusschock** [omni-us/jsonargparse#137]
Hi,

when having defined a function like 
```python

def train(
    train_root_path: str,
    val_root_path: str,
    model_n_dim: int,
    checkpoint_path: str,
    project_name: str,
    wandb_save_dir: str = "/tmp/tmp_wandb",
    mixed_precision: bool = True,
    device_id: int = 0,
    offset: int = 1,
    num_workers: int = 8,
    samples_per_volume: int = 50,
    num_save_procs: int = 0,
    num_stat_collection_procs: int = 0,
    class_names: Sequence[str] | None = None,
    **model_kwargs: Any,
) -> None:
    print('Function has been running')

def main():
    import jsonargparse
    jsonargpase.CLI(train)
   
if __name__ == '__main__':
    main()

```

and trying `python -m my_module.train -h` (which is the file above), I get the error 

```

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/medical_segmentation/train.py", line 150, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/medical_segmentation/train.py", line 146, in main
    jsonargparse.CLI(train)
  File "/opt/conda/lib/python3.8/site-packages/jsonargparse/cli.py", line 66, in CLI
    _add_component_to_parser(component, parser, as_positional, config_help)
  File "/opt/conda/lib/python3.8/site-packages/jsonargparse/cli.py", line 115, in _add_component_to_parser
    parser.add_function_arguments(component, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/jsonargparse/signatures.py", line 187, in add_function_arguments
    return self._add_signature_arguments([function],
  File "/opt/conda/lib/python3.8/site-packages/jsonargparse/signatures.py", line 264, in _add_signature_arguments
    self._add_signature_parameter(
  File "/opt/conda/lib/python3.8/site-packages/jsonargparse/signatures.py", line 375, in _add_signature_parameter
    raise ValueError(f'Required parameter without a type for {obj} parameter "{name}".')
ValueError: Required parameter without a type for <function train at 0x400206f280> parameter "train_root_path".
```

and I don't really understand why. Of course, I haven't specified it yet, but it definitely has a type and shouldn't `-h` list the options anyways?

**Comment by mauvilsa** [comment]
With the code snippet above I was unable to reproduce the problem. I managed to run without issue after fixing a couple of things. Note there is an inconsistency, the stack trace says python 3.8, but `Sequence[str] | None` would be a syntax error in that version. In python 3.10 where that syntax is valid, would not have worked because the union using `|` was not working. I have just released version 4.7.3 which fixes that, see #136. Maybe upgrade and try again.

**Comment by justusschock** [comment]
Thank you. I tried 4.7.3 and the issue still persists. I am not sure why.

Regarding the python version: There is a `from __future__ import annotations` import missing in this example which resolves the error. 

I'll investigate further!

**Comment by mauvilsa** [comment]
`from __future__ import annotations` currently is not supported and will not be added any time soon, see #120. The error you are getting is indeed quite misleading. I will look into having a more specific message for this.

**Comment by justusschock** [comment]
Thanks :) But I also tried it with python 3.10 and had the same issue (although the import was still in place).

**Comment by indigoviolet** [comment]
@mauvilsa just ran into this error message, and would like to see this message changed - it was quite confusing. Should this be re-opened?

**Comment by mauvilsa** [comment]
@indigoviolet created a pull request #240. Please review.

**Comment by mauvilsa** [comment]
@justusschock, @indigoviolet  support for future annotations in jsonargparse has been implemented, but not yet released, see #294. Can you please try it out? Just install as:

```
pip3 install "jsonargparse[signatures] @ https://github.com/omni-us/jsonargparse/zipball/future-annotations"
```
