### ISSUE TITLE
`TypeError: 'bool' object is not callable` on import on python 3.7 without `typing_extensions`

### ISSUE THREAD

**Issue by otaj** [omni-us/jsonargparse#178]
## 🐛 Bug report

When running on `python<3.8`, where there is not `typing.final` without `typing_extensions` installed, importing `jsonargparse` produces the `TypeError`.

```
   File ".actions/assistant.py", line 17, in <module>
    import jsonargparse
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/jsonargparse/__init__.py", line 9, in <module>
    from .actions import *
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/jsonargparse/actions.py", line 12, in <module>
    from .loaders_dumpers import get_loader_exceptions, load_value
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/jsonargparse/loaders_dumpers.py", line 10, in <module>
    from .optionals import import_jsonnet, omegaconf_support
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/jsonargparse/optionals.py", line 45, in <module>
    if not getattr(final(Namespace()), '__final__', False):
```

The problem is in the line above (44 in `optionals.py`), where fallback import returns `False`, which is definitely not callable.

### To reproduce

install jsonargparse on python 3.7 without any extras and import

### Expected behavior

No `TypeError`

### Environment

- jsonargparse version (e.g., 4.8.0): latest at the moment of writing (4.15.2)
- Python version (e.g., 3.9): 3.7
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`): `pip install jsonargparse`
- OS (e.g., Linux): Any

**Comment by mauvilsa** [comment]
This is fixed in commit https://github.com/omni-us/jsonargparse/commit/bdc528b8f1d1d62ccc0b08a944cc016e10f83a93.

**Comment by otaj** [comment]
Awesome, thanks!

**Comment by carmocca** [comment]
@otaj we should revert https://github.com/Lightning-AI/lightning/commit/bbf34fc7c4319ab3c002f10bdd901f1ba3693cb5 now

**Comment by otaj** [comment]
@carmocca I don't think we should, since this is still not available on PyPI yet. Once it will become available, we can revert it
